# Generated by Django 3.2.8 on 2021-12-03 03:27

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog_categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('body_content', models.TextField()),
                ('post_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(blank=True, null=True, related_name='articles', to='blog_categories.Categories')),
            ],
            options={
                'verbose_name': 'Articles',
                'verbose_name_plural': 'Articles',
                'ordering': ['-created'],
            },
        ),
    ]
