# Generated by Django 3.2.8 on 2021-11-23 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_alter_categories_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='body_content',
        ),
    ]
