# Generated by Django 3.2.8 on 2021-11-23 02:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_alter_posts_body_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='body_content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
