# Generated by Django 3.2.8 on 2021-11-26 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0007_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Categories', 'verbose_name_plural': 'Categories'},
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
